package com.agsnasoft.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.declarative.Design;
import org.vaadin.viritin.fields.LabelField;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RecibosGUI extends GridLayout {
	protected HorizontalLayout colRow2;
	protected LabelField lblMutualista;
	protected LabelField lblMutualistaDescription;
	protected HorizontalSplitPanel spliterColRow2;
	protected LabelField lblNif;
	protected LabelField lblNifDescription1;
	protected HorizontalLayout colRow3;
	protected LabelField lblOAsegurado;
	protected LabelField lblOAseguradoDescription;
	protected HorizontalSplitPanel spliterColRow3;
	protected LabelField lblFecEfecto;
	protected LabelField lblFecEfectoDescription;
	protected HorizontalLayout colRow1;
	protected LabelField lblRamo;
	protected LabelField lblRamoDescription;
	protected HorizontalSplitPanel spliterColRow1;
	protected LabelField lblNPoliza;
	protected LabelField lblNPolizaDescription1;
	protected HorizontalLayout colRow4;
	protected LabelField lblModalidad;
	protected LabelField lblModalidadDescription;
	protected HorizontalSplitPanel spliterColRow31;
	protected LabelField lblFranquicia;
	protected LabelField lblFranquiciaDescription1;
	protected LabelField lblVencimiento;
	protected LabelField lblVencimientoDescription;
	protected HorizontalLayout colRow5;
	protected LabelField lblDirPago;
	protected LabelField lblDirPagoDescription;
	protected HorizontalSplitPanel spliterColRow5;
	protected LabelField lblCcc;
	protected LabelField lblCccDescription;

	public RecibosGUI() {
		Design.read(this);
	}
}
